services:
  - type: web
    name: financeapp
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    disk:
      name: financeapp-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://+:8080
    healthCheckPath: /
